### ISSUE TITLE
only work on rust v1.81.0 now

### ISSUE THREAD

**Issue by vivianjeng** [zkmopro/rust-rapidsnark#5]
- When using later version, the Android runtime doesn't find the linked library

**Comment by vivianjeng** [comment]
upgrade for 1.89.0
build for iOS device
error messages
```sh
Undefined symbols for architecture arm64:
            "___chkstk_darwin", referenced from:
                Groth16::Verifier<AltBn128::Engine>::finalExponentiation(F12Field<F6Field<F2Field<RawFq>>>::Element&) in librust_rapidsnark-423fbb803790cb88.rlib[14](verifier.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by vivianjeng** [comment]
fixed by #9
